name: Draft PDF
<<<<<<< HEAD
on:
  push:
    branches:
      - main
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml
=======
on: [push]
>>>>>>> 1f6d9be7740f5a5954e9d71be459b219e191fe66

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
<<<<<<< HEAD
          paper-path: ./paper/paper.md
=======
          paper-path: paper/paper.md
>>>>>>> 1f6d9be7740f5a5954e9d71be459b219e191fe66
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
<<<<<<< HEAD
          path: ./paper/paper.pdf
=======
          path: paper/paper.pdf
>>>>>>> 1f6d9be7740f5a5954e9d71be459b219e191fe66
